name: Bending
main: net.bendercraft.spigot.bending.Bending
authors: [Noko, Koudja]
version: 7.3.0
api-version: 1.15
depend: [ProtocolLib]
softdepend: [WorldGuard,WGCustomFlags,WorldEdit,CoreProtect,Citizens,Factions]
commands:
    bending:
        description: Chooses the many features of Bending.
        aliases: [b, bend, tla, mtla, minecrafttla]
        usage: /bending help
permissions:
  bending.air.*:
    description: Allows all air bending.
    default: false
    children:
      bending.air: true
      bending.air.AirSwipe: true
      bending.air.AirBubble: true
      bending.air.AirShield: true
      bending.air.AirSuction: true
      bending.air.AirSpeed: true
      bending.air.Tornado: true
      bending.air.AirBlast: true
      bending.air.Passive: true
      bending.air.AirSpout: true
      bending.air.AirBurst: true
      bending.air.AirScooter: true
      bending.air.AirManipulation: true
      bending.air.Suffocate: true
  bending.fire.*:
    description: Allows all fire bending.
    default: false
    children:
      bending.message.daymessage: true
      bending.fire: true
      bending.fire.Blaze: true
      bending.fire.HeatControl: true
      bending.fire.FireJet: true
      bending.fire.FireBlast: true
      bending.fire.Passive: true
      bending.fire.Illumination: true
      bending.fire.WallOfFire: true
      bending.fire.Lightning: true
      bending.fire.FireBurst: true
      bending.fire.FireShield: true
      bending.fire.FireBlade: true
      bending.fire.Combustion: true
  bending.water.*:
    description: Allows all water bending.
    default: false
    children:
      bending.message.nightmessage: true
      bending.water: true
      bending.water.PhaseChange: true
      bending.water.HealingWaters: true
      bending.water.Plantbending: true
      bending.water.WaterBubble: true
      bending.water.WaterManipulation: true
      bending.water.Surge: true
      bending.water.Passive: true
      bending.water.WaterPassive: true
      bending.water.FastSwimming: true
      bending.water.WaterSpout: true
      bending.water.IceSpike: true
      bending.water.Torrent: true
      bending.water.OctopusForm: true
      bending.water.IceSwipe: true
  bending.earth.*:
    description: Allows all earth bending.
    default: false
    children:
      bending.earth: true
      bending.earth.Catapult: true
      bending.earth.EarthBlast: true
      bending.earth.RaiseEarth: true
      bending.earth.EarthGrab: true
      bending.earth.EarthTunnel: true
      bending.earth.Collapse: true
      bending.earth.Passive: true
      bending.earth.Tremorsense: true
      bending.earth.EarthArmor: true
      bending.earth.Shockwave: true
      bending.earth.MetalBending: true
      bending.earth.LavaTrain: true
  bending.master.*:
    description: Allows all chiblocking abilities.
    default: false
    children:
      bending.master: true
      bending.master.RapidPunch: true
      bending.master.HighJump: true
      bending.master.Paralyze: true
      bending.master.SmokeBomb: true
      bending.master.Dash: true
      bending.master.PoisonnedDart: true
      bending.master.PlasticBomb: true
  bending.*:
    description: Allows all bending.
    default: false
    children:
      bending.earth.*: true
      bending.water.*: true
      bending.fire.*: true
      bending.air.*: true
      bending.master.*: true
      
  bending.admin:
    description: Allows all commands.
    default: op
    children:
      bending.command.remove: true
      bending.command.reload: true
      bending.command.choose.other: true
      bending.command.rechoose: true
      bending.command.add: true
      bending.command.add.other: true
      bending.command.who: true
      bending.command.affinity: true
      bending.command.path: true
      bending.command.learning: true
      bending.command: true
      
  bending.command:
    description: Allows all user commands.
    default: true
    children:
      bending.command.choose: true
      bending.command.clear: true
      bending.command.display: true
      bending.command.bind: true
      bending.command.help: true
      bending.command.toggle: true
      bending.command.version: true
      bending.command.available: true
      bending.command.cooldown: true
      bending.command.deck: true

  bending.canequip.*:
    description: Allow user to equip stuff that have been denied for players
    default: false
    children:
      bending.canequip.elytra: true
  bending.canequip.elytra:
    description: Allow user to equip elytra
    default: false

# AIRBENDING PERMISSIONS
  bending.air:
    description: Allows being an Airbender.
    default: true
    children:
      bending.air.passive: true
  bending.air.AirSwipe:
    description: Allows the use of AirSwipe.
    default: false
  bending.air.AirBubble:
    description: Allows the use of AirBubble.
    default: false
  bending.air.passive:
    description: Allows the use of AirPassive.
    default: true
  bending.air.AirGlide:
    description: Allows the use of the Glide
    default: true
  bending.air.AirShield:
    description: Allows the use of AirShield.
    default: false
  bending.air.AirSuction:
    description: Allows the use of AirSuction.
    default: false
  bending.air.AirSpout:
    description: Allows the use of AirSpout.
    default: true
  bending.air.AirScooter:
    description: Allows the use of AirScooter.
    default: false
  bending.air.AirSpeed:
    description: Allows the use of Speed.
    default: true
  bending.air.Tornado:
    description: Allows the use of Tornado.
    default: false
  bending.air.AirBlast:
    description: Allows the use of AirBlast.
    default: true
  bending.air.AirBurst:
    description: Allows the use of AirBurst.
    default: false
  bending.air.AirManipulation:
    description: Allows the use of AirManipulation.
    default: false
  bending.air.Suffocate:
   description: Allows the use of Suffocate.
   default: false
    
# FIREBENDING PERMISSIONS
  bending.fire:
    description: Allows being a Firebender.
    default: true
  bending.fire.blaze:
    description: Allows the use of Blaze.
    default: true
  bending.fire.heatcontrol:
    description: Allows the use of ControlHeat.
    default: true
  bending.fire.FireJet:
    description: Allows the use of FireJet.
    default: false
  bending.fire.fireblast:
    description: Allows the use of FireBlast
    default: true
  bending.fire.Passive:
    description: Allows the use of Passive.
    default: true
  bending.fire.Illumination:
    description: Allows the use of Illumination.
    default: false
  bending.fire.WallOfFire:
    description: Allows the use of WallOfFire.
    default: false
  bending.fire.Lightning:
    description: Allows the use of Lightning.
    default: false
  bending.fire.FireBurst:
    description: Allows the use of FireBurst.
    default: false
  bending.fire.FireShield:
    description: Allows the use of FireShield.
    default: false
  bending.fire.FireBlade:
    description: Allows the use of FireBlade.
    default: false
  bending.fire.Combustion:
    description: Allows the use of Combustion.
    default: false
    
# WATERBENDING PERMISSIONS
  bending.water:
    description: Allows being a Waterbender.
    default: true
  bending.water.PhaseChange:
    description: Allows the use of PhaseChange.
    default: false
  bending.water.HealingWaters:
    description: Allows the use of HealingWaters.
    default: true
  bending.water.Plantbending:
    description: Allows the use of Plantbending.
    default: true
  bending.water.WaterBubble:
    description: Allows the use of WaterBubble.
    default: false
  bending.water.WaterManipulation:
    description: Allows the use of WaterManipulation.
    default: true
  bending.water.Passive:
    description: Allows the use of WaterPassive.
    default: true
  bending.water.WaterPassive:
    description: Allows the use of WaterPassive.
    default: true
  bending.water.FastSwimming:
    description: Allows the use of Dolphin
    default: true
  bending.water.WaterSpout:
    description: Allows the use of WaterSpout.
    default: true
  bending.water.Surge:
    description: Allows the use of Surge.
    default: false
  bending.water.Bloodbending:
    description: Allows the use of Bloodbending.
    default: false
  bending.water.OctopusForm:
    description: Allows the use of OctopusForm.
    default: false
  bending.water.Torrent:
    description: Allows the use of Torrent.
    default: false
  bending.water.IceSpike:
    description: Allows the use of IceSpike.
    default: false
  bending.water.IceSwipe:
    description: Allows the use of IceSwipe.
    default: false
    
# EARTHBENDING PERMISSIONS
  bending.earth:
    description: Allows being an Earthbender.
    default: true
  bending.earth.Catapult:
    description: Allows the use of Catapult.
    default: false
  bending.earth.EarthBlast:
    description: Allows the use of EarthBlast.
    default: true
  bending.earth.RaiseEarth:
    description: Allows the use of RaiseEarth.
    default: true
  bending.earth.Passive:
    description: Allows the use of EarthPassive.
    default: true
  bending.earth.EarthPassive:
    description: Allows the use of EarthPassive.
    default: true
  bending.earth.EarthTunnel:
    description: Allows the use of EarthTunnel.
    default: false
  bending.earth.Collapse:
    description: Allows the use of PatchTheEarth.
    default: true
  bending.earth.EarthGrab:
    description: Allows the use of EarthGrab.
    default: false
  bending.earth.Tremorsense:
    description: Allows the use of Tremorsense.
    default: false
  bending.earth.Shockwave:
    description: Allows the use of Shockwave.
    default: false
  bending.earth.EarthArmor:
    description: Allows the use of EarthArmor.
    default: false
  bending.earth.MetalBending:
    description: Allows the use of MetalBending.
    default: false
  bending.earth.LavaTrain:
    description: Allows the use of LavaTrain.
    default: false
  bending.earth.LavaBlast:
    description: Allows the use of LavaBlast
    default: false
    
# CHIBLOCKING PERMISSIONS
  bending.master:
    description: Allows being a Chiblocker.
    default: true
  bending.master.passive:
    description: Allows the use of the Chi Speed
    default: true
  bending.master.DirectHit:
    description: Allows the use of DirectHit
    default: true
  bending.master.HighJump:
    description: Allows the use of HighJump
    default: true
  bending.master.VitalPoint:
    description: Allows the use of Paralyze
    default: true
  bending.master.SmokeBomb:
    description: Allows the use of SmokeBomb
    default: false
  bending.master.Dash:
    description: Allows the use of Dash.
    default: false
  bending.master.PoisonnedDart:
    description: Allows the use of PoisonnedDart
    default: false
  bending.master.PlasticBomb:
    description: Allows the use of the C4
    default: false
  bending.master.Release:
    description: Allows the use of the Release
    default: true

# ENERGY PERMISSIONS
  bending.energy.avatarstate:
    description: Allows the use of the AvatarState
    default: op

# ADMIN PERMISSIONS
  bending.command.remove: 
    description: Allows the use of /bending remove <player>
    default: op
  bending.command.reload:
    description: Allows the use of /bending reload
    default: op
  bending.admin.rechoose:
    description: Allows the use of /bending choose <element> after choosing one.
    default: op
  bending.command.choose.other:
    description: Allows the use of /bending choose <player> <element>
    default: op
  bending.command.add: 
    description: Allows the use of /bending add <element>
    default: op
  bending.command.add.other:
    description: Allows to add elements to other player
    default: op
  bending.command.path:
    description: Allows to list path
    default: op
  bending.command.path.admin:
    description: Allows to manage path
    default: op
  bending.command.affinity:
    description: Allows to choose an affinity
    default: op
  bending.command.affinity.other:
    description: Allows to use affinity command on other people
    default: op
  bending.command.who:
    description: Allows the use of /bending who
    default: op
  bending.command.learning:
    default: op
    description: Allows the use of /bending learning

# COMMAND PERMISSIONS
  bending.command.choose:
    description: Allows the use of /bending choose <element>
    default: true
  bending.command.display: 
    description: Allows the use of /bending display <element>
    default: true
  bending.command.clear: 
    description: Allows the use of /bending clear 
    default: true
  bending.command.deck:
    description: Allows the use of /bending deck
    default: true
  bending.command.bind:
    description: Allows the use of /bending bind <ability>
    default: true
  bending.command.help:
    description: Allows the use of /bending help
    default: true
  bending.command.toggle:
    description: Allows the use of /bending toggle
    default: true
  bending.command.version:
    description: Allows the use of /bending version
    default: true
  bending.command.cooldown:
    description: Allows the use of /bending cooldown
    default: true
  bending.command.available:
    description: Allows the use of available command
    default: true
  bending.command.credentials:
    description: Allows the use of credentials command
    default: true

  bending.immune:
    description: Make the player that has that permission to be immune to bending abilities
    default: false
  bending.protection.bypass:
    description: Players with this permission are not affected by world guard protection
    default: false
  bending.denyitem.bypass:
    description: Players with this permission are not affected by automatic items removal
    default: false
    
  bending.message.daymessage:
    description: Allows receipt of the sun rising and falling for firebenders
    default: true
  bending.message.nightmessage:
    description: Allows receipt of the moon rising and falling for waterbenders
    default: true
